jobs:
 build:
   runs-on: ubuntu-latest
   steps:
 
   - name: Creating kind cluster
     uses: helm/kind-action@v1.0.0-rc.1
 
   - name: Print cluster information
     run: |
       kubectl config view
       kubectl cluster-info
       kubectl get nodes
       kubectl get pods -n kube-system
       helm version
       kubectl version
 
   - uses: actions/checkout@v2
